# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: false

# Setup
title:            Ferdian Jovan
tagline:          'My Personal Website'
description:      'Assistant Professor of <a href="https://www.abdn.ac.uk/ncs/" target="_blank">School of Computing and Natural Sciences</a>, <a href="https://www.abdn.ac.uk/" target="_blank">University of Aberdeen</a>'
url:              https://ferdianjovan.github.io
baseurl:          /


author:
  name:           'Ferdian Jovan'
  url:            https://linkedin.com/in/ferdian-jovan/

plugins:          [jekyll-paginate, jekyll-gists]
paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/ferdianjovan/
